### PR TITLE
Add Compose plugins

### PR DESCRIPTION
**Pull request by 4face-studi0**
This PR makes the Project Compose-ready by:
* adding Compose to the `AndroidAppPlugin`, now `AndroidComposeAppPlugin` (id `aditogether.android.app` -> `aditogheter.android.compose.app`)
* adding `AndroidComposeLibraryPlugin` (id `aditogether.android.compose.library`)

### CODE REVIEW

**Comment by fondesa** [comment]
I wouldn't add `AndroidAppComposePlugin` and `AndroidLibraryComposePlugin` because the approach of combining custom plugins in a unique one doesn't scale IMHO.
Let's say we add Robolectric for Android tests. Following this approach, we would need to create the matrix between the xisting plugins and the Robolectric ones (e.g. `AndroidLibraryComposeRobolectricPlugin`, etc...).

What I'd propose instead is having just `AndroidComposePlugin` and users can apply plugins when needed:
```
plugins {
  id "aditogether.android.library"
  id "aditogether.android.compose"
}
```

Having plugins separate is the purpose of plugins IMHO, otherwise we could just have one single big plugin with config options.

**Comment by 4face-studi0** [comment]
> I wouldn't add `AndroidAppComposePlugin` and `AndroidLibraryComposePlugin` because the approach of combining custom plugins in a unique one doesn't scale IMHO. Let's say we add Robolectric for Android tests. Following this approach, we would need to create the matrix between the existing plugins and the Robolectric ones (e.g. `AndroidLibraryComposeRobolectricPlugin`, etc...).
> 
> What I'd propose instead is having just `AndroidComposePlugin` and users can apply plugins when needed:
> 
> ```
> plugins {
>   id "aditogether.android.library"
>   id "aditogether.android.compose"
> }
> ```
> 
> Having plugins separate is the purpose of plugins IMHO, otherwise we could just have one single big plugin with config options.

Thank you! That's great input! I'm just wondering whether we could seek a balance between extensibility/versatility and simplicity.
Taking as an example what you just mentioned, Robolectric: I would imagine that if we decide to use Robolectric, that would be used "everywhere", so with separate plugins, we could have 2 scenarios:
1) Have `plugins { library, compose, robolectric, others }` everywhere
2) Have `plugins { library, compose }` and others added as needed

Both scenarios could have negative consequences, like:
* I am to write tests for `moduleA`; there is no Robolectric applied, so I don't know about it and I just use "something else" (like a conventional instrumented test)
* I am to create `moduleB`, so I copy-paste the list of plugins from `moduleA`, which doesn't have Robolectric; afterward, we add Robolectric to `moduleB`, so we have 2 different examples of a setup for an Android module. Later again, we add `SuperRobolectric` and use it in `moduleC`. And so on...

I'm not advocating for one way over the other, just making my thoughts public 🙂

**Comment by fondesa** [comment]
>  I'm just wondering whether we could seek a balance between extensibility/versatility and simplicity.

Usually the solution to this is having a plugin which defines what a "feature" for AdiTogether is, instead of grouping some of the frameworks used based on the average number of uses.

This is the usual setup I've seen in the past for cases like this:

_Plugins which configure a specific framework_
```
foo.android.library
foo.android.app
foo.android.compose
foo.android.coverage
foo.android.robolectric
```

_Plugins which configure our product modules_
```
foo.feature.android
foo.core
```

And configured like this:
```
plugins {
  id "foo.feature.android"
}

// This is just an example, it can have defaults. E.g. by default Robolectric is turned on.
fooAndroid {
  compose = true
  robolectric = true
}
```

**Comment by 4face-studi0** [comment]
Thank you! That solves my concerns 🥳

I'll apply the changes!

**Review by fondesa — APPROVED** [review]

**Pull request merged**
