### PR TITLE
Enable auto-correct with Detekt in pre-commit.sh

### PR DESCRIPTION
**Pull request by 4face-studi0**
This PR adds auto-correct with Detekt in pre-commit.sh.

When a commit is done and Detekt found issues on the committed files, it will try to correct them automatically, if possible.

### CODE REVIEW

**Comment by fondesa** [comment]
Personally I didn't enable that on purpose when I first added the pre-commit scripts.
IMHO formatting the files should be done intentionally, invoking something, not under the hood, since it's something that changes the code so you may want to be sure to review that afterwards.
Said that, I'm fine even enabling this in the pre-commit script but I wanted to clarify why I didn't in the first place.

**Comment by 4face-studi0** [comment]
@fondesa 

I see; thanks for the explanation! I found it useful on my project, while I was doing some refactors using the IDE tools, and, since the IDEA code-style doesn't cover as much as Detekt does, some Detekt issues were introduced: enabling auto-correct on pre-commit, allowed me to avoid running Detekt on the whole project.

On the other side, I share your thoughts.

Let's wait for other inputs/data, then.
Should we open a discussion?

**Comment by mcatta** [comment]
I agree with @fondesa, I remember that I did the same discussion in past with other colleagues, and we concluded that is better to throw a failure in pre-commit without any auto-correction, in this way the developer should have more control over his/her staged files.

IMHO auto-correct is definitely useful, but pre-commit I think isn't the right place for it.

**Comment by 4face-studi0** [comment]
Aight, let's close this then, it seems more reasonable that one can run it manually on its side ✌️

**Pull request closed without merging**
